### ISSUE TITLE
Upgrade to 11.0 SP9

### ISSUE THREAD

**Issue by cgillis-aras** [ArasLabs/email-language-chooser#1]
This needs to be tested against 11.0 SP9 and upgraded if necessary.

**Comment by AngelaIp** [comment]
Hi,
with some minor changes this will also work for SP9, see my pull request.

One remark:
This project is at the first glance 'yet another GUI' example. But one interesting feature isn´t mentioned in the readme.
This example shows how to handle self created HTML-buttons! Handling HTML-elements is a little bit different than handling the standard Aras GUI elements.

**Comment by EliJDonahue** [comment]
Resolved by pull request #2. Closing this issue.
